import type { RawReviewComment } from "../core/types.js";

const MIN_LENGTH = 50;

const APPROVAL_PATTERNS = [
  /^lgtm\b/i,
  /^looks good/i,
  /^approved\b/i,
  /^no issues/i,
  /^ship it/i,
  /^\+1\s*$/,
  /^:thumbsup:/,
];

const SUMMARY_HEADING_PATTERNS = [
  /^##\s*Summary/im,
  /^##\s*Walkthrough/im,
  /^##\s*PR Summary/im,
  /^##\s*Changes/im,
];

const BOT_FOOTER_PATTERNS = [
  /---\n.*generated by/i,
  /\*\*Full Coverage Report\*\*/,
  /<details>[\s\S]*?<summary>.*walkthrough/i,
  /<!-- .* -->/,
  /\[!TIP\]/,
  /This is an auto-generated/i,
];

export type DiscardedComment = {
  id: string;
  reason: string;
};

export function filterNoise(
  comments: RawReviewComment[],
): { kept: RawReviewComment[]; discarded: DiscardedComment[] } {
  const kept: RawReviewComment[] = [];
  const discarded: DiscardedComment[] = [];

  for (const comment of comments) {
    const stripped = stripMarkdown(comment.body).trim();

    // Min length
    if (stripped.length < MIN_LENGTH) {
      discarded.push({ id: comment.id, reason: "too_short" });
      continue;
    }

    // Approval patterns
    if (APPROVAL_PATTERNS.some((p) => p.test(stripped))) {
      discarded.push({ id: comment.id, reason: "approval_only" });
      continue;
    }

    // Summary-only (bot PR summaries, not actual review comments)
    if (isSummaryOnly(comment.body)) {
      discarded.push({ id: comment.id, reason: "summary_only" });
      continue;
    }

    // Bot footer only
    if (isBotFooterOnly(comment.body)) {
      discarded.push({ id: comment.id, reason: "bot_footer" });
      continue;
    }

    kept.push(comment);
  }

  return { kept, discarded };
}

function stripMarkdown(text: string): string {
  return text
    .replace(/```[\s\S]*?```/g, "") // code blocks
    .replace(/`[^`]+`/g, "") // inline code
    .replace(/!\[.*?\]\(.*?\)/g, "") // images
    .replace(/\[.*?\]\(.*?\)/g, "") // links
    .replace(/#+\s/g, "") // headings
    .replace(/[*_~]+/g, "") // bold/italic/strikethrough
    .replace(/<[^>]+>/g, "") // HTML tags
    .trim();
}

function isSummaryOnly(body: string): boolean {
  const hasSummaryHeading = SUMMARY_HEADING_PATTERNS.some((p) => p.test(body));
  if (!hasSummaryHeading) return false;

  // If it has a summary heading but no actionable review content,
  // it's likely a bot-generated PR summary, not a review
  const lines = body.split("\n").filter((l) => l.trim().length > 0);
  const headingLines = lines.filter((l) => /^#+\s/.test(l));
  // If most of the content is headings + lists, it's a summary
  return headingLines.length >= lines.length * 0.3;
}

function isBotFooterOnly(body: string): boolean {
  return BOT_FOOTER_PATTERNS.some((p) => p.test(body)) && body.trim().length < 200;
}
