import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  findPullRequestTemplate,
  buildBundledPrBody,
  buildSinglePrBody,
  buildBundledPrTitle,
  buildSinglePrTitle,
  formatConfidence,
  DECISION_LINE_RE,
} from "./template.js";
import type { PromotionCandidate } from "../core/types.js";

const baseCandidate = (overrides: Partial<PromotionCandidate> = {}): PromotionCandidate & { targetFile: string } => ({
  id: "candidate_001",
  repo: "owner/repo",
  clusterId: "cluster_x",
  summary: "Use shared API client instead of direct fetch",
  target: "agents",
  confidence: 0.91,
  reasoning: "Cross-feature convention — feature code repeatedly bypassed the shared client.",
  alternatives: [{ target: "path_scoped_rule", reason: "examples across multiple features" }],
  occurrences: [
    { prNumber: 347, path: "src/features/quest/api.ts", url: "https://github.com/owner/repo/pull/347", excerpt: "", authorLogin: "coderabbit[bot]", createdAt: "2026-05-01" },
    { prNumber: 352, path: "src/features/gacha/api.ts", url: "https://github.com/owner/repo/pull/352", excerpt: "", authorLogin: "coderabbit[bot]", createdAt: "2026-05-02" },
  ],
  draft: { targetFile: "AGENTS.md", content: "## API access\n- Use shared client.\n", insertionHint: "" },
  status: "candidate",
  ...overrides,
  targetFile: "AGENTS.md",
});

describe("findPullRequestTemplate", () => {
  let tmp: string;

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "promote-pr-test-"));
  });

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("returns null when no template exists", () => {
    expect(findPullRequestTemplate(tmp)).toBeNull();
  });

  it("finds .github/PULL_REQUEST_TEMPLATE.md", () => {
    mkdirSync(join(tmp, ".github"), { recursive: true });
    writeFileSync(join(tmp, ".github/PULL_REQUEST_TEMPLATE.md"), "## Checklist\n- [ ] tests", "utf-8");
    const found = findPullRequestTemplate(tmp);
    expect(found?.path).toBe(".github/PULL_REQUEST_TEMPLATE.md");
    expect(found?.body).toContain("Checklist");
  });

  it("finds lowercase variant", () => {
    mkdirSync(join(tmp, ".github"), { recursive: true });
    writeFileSync(join(tmp, ".github/pull_request_template.md"), "lower", "utf-8");
    const found = findPullRequestTemplate(tmp);
    expect([
      ".github/PULL_REQUEST_TEMPLATE.md",
      ".github/pull_request_template.md",
    ]).toContain(found?.path);
    expect(found?.body).toBe("lower");
  });

  it("prefers .github/PULL_REQUEST_TEMPLATE.md over docs/ variant", () => {
    mkdirSync(join(tmp, ".github"), { recursive: true });
    mkdirSync(join(tmp, "docs"), { recursive: true });
    writeFileSync(join(tmp, ".github/PULL_REQUEST_TEMPLATE.md"), "github-one", "utf-8");
    writeFileSync(join(tmp, "docs/PULL_REQUEST_TEMPLATE.md"), "docs-one", "utf-8");
    const found = findPullRequestTemplate(tmp);
    expect(found?.body).toBe("github-one");
  });
});

describe("buildBundledPrBody — without prefilled header", () => {
  const date = new Date("2026-05-23T09:00:00Z");

  it("leads with the candidate list, not boilerplate", () => {
    const body = buildBundledPrBody({
      candidates: [baseCandidate()],
      stats: { prCount: 5 },
      sinceDays: 60,
      date,
    });

    // The decision list must come before the evidence detail and the footer,
    // because that ordering is the point of the layout.
    expect(body.indexOf("## Candidates")).toBeLessThan(body.indexOf("## Evidence"));
    expect(body.indexOf("## Evidence")).toBeLessThan(body.indexOf("Generated by"));
    expect(body).toContain("Use shared API client");
    expect(body).toContain("`AGENTS.md`");
    expect(body).toContain("#347");
  });

  it("drops the per-week boilerplate sections", () => {
    const body = buildBundledPrBody({ candidates: [baseCandidate()], sinceDays: 60, date });

    expect(body).not.toContain("## Testing");
    expect(body).not.toContain("## Memory promotion details");
  });

  it("renders one checked decision line per candidate", () => {
    const body = buildBundledPrBody({
      candidates: [baseCandidate(), baseCandidate({ id: "candidate_002", summary: "Second one" })],
      sinceDays: 60,
      date,
    });

    const lines = body.split("\n").filter((l) => DECISION_LINE_RE.test(l));

    expect(lines).toHaveLength(2);
    expect(lines[0]).toContain("`candidate_001`");
    expect(lines[1]).toContain("`candidate_002`");
    // Everything proposed starts checked; the reviewer unchecks to reject.
    expect(lines.every((l) => l.startsWith("- [x]"))).toBe(true);
  });

  it("round-trips its own decision lines through the parser regex", () => {
    const body = buildBundledPrBody({ candidates: [baseCandidate()], sinceDays: 60, date });
    const line = body.split("\n").find((l) => l.includes("candidate_001") && l.startsWith("- ["));

    expect(line).toBeDefined();
    expect(DECISION_LINE_RE.exec(line!)?.[2]).toBe("candidate_001");
  });

  it("names the digest in the footer", () => {
    const body = buildBundledPrBody({
      candidates: [baseCandidate()],
      sinceDays: 60,
      date,
      digestPath: "docs/promote/digests/2026-05-23.md",
    });

    expect(body).toContain("docs/promote/digests/2026-05-23.md");
  });

  it("caps evidence at 5 with an overflow note", () => {
    const many = baseCandidate({
      occurrences: Array.from({ length: 8 }, (_, i) => ({
        prNumber: i + 1,
        url: `https://github.com/owner/repo/pull/${i + 1}`,
        excerpt: "",
        authorLogin: "bot",
        createdAt: "2026-05-01",
      })),
    });

    expect(buildBundledPrBody({ candidates: [many], sinceDays: 60, date })).toContain("and 3 more");
  });

  it("counts distinct PRs, not occurrences, on the decision line", () => {
    const sameP = baseCandidate({
      occurrences: [
        { prNumber: 7, url: "u", excerpt: "", authorLogin: "bot", createdAt: "2026-05-01" },
        { prNumber: 7, url: "u", excerpt: "", authorLogin: "bot", createdAt: "2026-05-02" },
        { prNumber: 9, url: "u", excerpt: "", authorLogin: "bot", createdAt: "2026-05-03" },
      ],
    });
    const line = buildBundledPrBody({ candidates: [sameP], sinceDays: 60, date })
      .split("\n")
      .find((l) => DECISION_LINE_RE.test(l))!;

    expect(line).toContain("2 PRs");
  });

  describe("not-proposed section", () => {
    it("is omitted when nothing was skipped", () => {
      const body = buildBundledPrBody({ candidates: [baseCandidate()], sinceDays: 60, date });

      expect(body).not.toContain("## Not proposed");
    });

    it("groups skipped patterns by reason", () => {
      const body = buildBundledPrBody({
        candidates: [baseCandidate()],
        sinceDays: 60,
        date,
        skipped: [
          { summary: "Too vague to act on", reason: "not-promotable" },
          { summary: "Barely repeated", reason: "low-confidence", confidence: 0.4 },
        ],
      });

      expect(body).toContain("## Not proposed");
      expect(body).toContain("2 patterns were considered and left out");
      expect(body).toContain("Not a durable convention");
      expect(body).toContain("Below the confidence floor");
      expect(body).toContain("Barely repeated (0.40)");
    });

    it("leaves classify failures out — they are errors, not judgements", () => {
      const body = buildBundledPrBody({
        candidates: [baseCandidate()],
        sinceDays: 60,
        date,
        skipped: [{ summary: "failed: timeout", reason: "classify-failed" }],
      });

      expect(body).not.toContain("## Not proposed");
    });
  });
});

describe("buildBundledPrBody — with prefilled header (LLM output)", () => {
  const date = new Date("2026-05-23T09:00:00Z");

  it("keeps the team's template verbatim and still appends the candidate list", () => {
    const prefilled =
      "## Summary\n\nLLM-written summary that fills the team's template.\n\n## Checklist\n\n- [ ] reviewed manually";
    const body = buildBundledPrBody({
      candidates: [baseCandidate()],
      sinceDays: 60,
      date,
      prefilledHeader: prefilled,
    });

    expect(body).toContain("LLM-written summary that fills the team's template.");
    expect(body).toContain("- [ ] reviewed manually");
    expect(body).toContain("## Candidates");
    expect(body).toContain("## Evidence");
  });

  it("does not emit its own intro when a header is prefilled", () => {
    const body = buildBundledPrBody({
      candidates: [baseCandidate()],
      sinceDays: 60,
      date,
      prefilledHeader: "## Custom team section\n\nFilled by LLM.",
    });

    expect(body).toContain("## Custom team section");
    expect(body).not.toContain("repeated AI review pattern");
  });

  it("does not mistake a template's own checkbox for a decision line", () => {
    // The team's template may contain task lists of its own; only lines
    // naming a candidate ID are decisions.
    const body = buildBundledPrBody({
      candidates: [baseCandidate()],
      sinceDays: 60,
      date,
      prefilledHeader: "## Checklist\n\n- [ ] reviewed manually\n- [x] CODEOWNERS approved",
    });

    const decisions = body.split("\n").filter((l) => DECISION_LINE_RE.test(l));

    expect(decisions).toHaveLength(1);
    expect(decisions[0]).toContain("candidate_001");
  });
});

describe("buildSinglePrBody", () => {
  it("renders standalone when no prefilled header", () => {
    const body = buildSinglePrBody({
      candidate: baseCandidate(),
      date: new Date("2026-05-23T09:00:00Z"),
    });
    expect(body).toContain("## Summary");
    expect(body).toContain("Use shared API client");
    expect(body).toContain("## Evidence");
  });

  it("uses prefilled header when provided", () => {
    const body = buildSinglePrBody({
      candidate: baseCandidate(),
      date: new Date("2026-05-23T09:00:00Z"),
      prefilledHeader: "## Custom\n\nLLM-filled.",
    });
    expect(body).toContain("## Custom");
    expect(body).toContain("LLM-filled.");
    expect(body).toContain("## Evidence");
  });
});

describe("formatConfidence", () => {
  it("trims float artifacts to 2 decimals", () => {
    // 0.9 + 0.05 in IEEE 754 → 0.9500000000000001
    expect(formatConfidence(0.9 + 0.05)).toBe("0.95");
  });

  it("preserves trailing zeros", () => {
    expect(formatConfidence(0.9)).toBe("0.90");
    expect(formatConfidence(1)).toBe("1.00");
  });

  it("rounds correctly at the boundary", () => {
    expect(formatConfidence(0.755)).toBe("0.76");
    expect(formatConfidence(0.754)).toBe("0.75");
  });
});

describe("title builders", () => {
  it("bundled title pluralizes", () => {
    const d = new Date("2026-05-23T09:00:00Z");
    expect(buildBundledPrTitle(d, 1)).toBe("promote: 1 memory update from 2026-05-23 scan");
    expect(buildBundledPrTitle(d, 3)).toBe("promote: 3 memory updates from 2026-05-23 scan");
  });

  it("single title truncates long summaries", () => {
    const long = "a".repeat(80);
    const title = buildSinglePrTitle({ summary: long });
    expect(title.length).toBeLessThanOrEqual("promote: ".length + 60);
    expect(title.endsWith("...")).toBe(true);
  });
});
