import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import type { PromotionCandidate, AnalysisStats } from "../core/types.js";
import { VERSION } from "../version.js";

const TEMPLATE_PATHS = [
  ".github/PULL_REQUEST_TEMPLATE.md",
  ".github/pull_request_template.md",
  "PULL_REQUEST_TEMPLATE.md",
  "pull_request_template.md",
  "docs/PULL_REQUEST_TEMPLATE.md",
  "docs/pull_request_template.md",
];

export function findPullRequestTemplate(cwd: string = process.cwd()): { path: string; body: string } | null {
  for (const rel of TEMPLATE_PATHS) {
    const full = resolve(cwd, rel);
    if (existsSync(full)) {
      try {
        const body = readFileSync(full, "utf-8");
        return { path: rel, body };
      } catch {
        continue;
      }
    }
  }
  return null;
}

export type BundledBodyInput = {
  candidates: Array<PromotionCandidate & { targetFile: string }>;
  stats?: Pick<AnalysisStats, "prCount">;
  sinceDays: number;
  date: Date;
  /**
   * The PR body header to use. Two ways to populate it:
   *   - LLM-filled template body (preferred when template exists): pass the
   *     output of fillTemplateWithLlm() here.
   *   - Raw template body: passed through verbatim. The detailed Memory
   *     promotion details appendix is always added below.
   * If undefined, a default "## Summary / Why / Changes / Testing" header is
   * emitted instead.
   */
  prefilledHeader?: string;
  digestPath?: string;
};

export function buildBundledPrBody(input: BundledBodyInput): string {
  const isoDate = input.date.toISOString().split("T")[0];
  const sections: string[] = [];

  if (input.prefilledHeader && input.prefilledHeader.trim().length > 0) {
    sections.push(input.prefilledHeader.trimEnd());
  } else {
    const buckets = buildBundledBuckets(input);
    sections.push("## Summary", buckets.description);
    sections.push("## Why", buckets.why);
    sections.push("## Changes", buckets.changes);
    sections.push("## Testing", buckets.testing);
  }

  sections.push("## Memory promotion details");
  sections.push(`Generated by \`promote-cli\` v${VERSION} from scan run on ${isoDate}.`);
  sections.push("### Bundled candidates");
  for (let i = 0; i < input.candidates.length; i++) {
    sections.push(renderCandidateBlock(input.candidates[i], i + 1));
  }
  sections.push("### Safety");
  const safetyLines = [`- This PR was generated. Each draft requires human review before merge.`];
  if (input.digestPath) {
    safetyLines.push(
      `- Full digest (skipped + \`needs_human_decision\` candidates included) is committed at \`${input.digestPath}\`.`,
    );
  }
  sections.push(safetyLines.join("\n"));

  return sections.join("\n\n") + "\n";
}

function buildBundledBuckets(input: BundledBodyInput): Record<"description" | "why" | "changes" | "testing", string> {
  const count = input.candidates.length;
  const prCount = input.stats?.prCount;

  const description =
    `\`promote-cli\` detected ${count} repeated AI review pattern(s)` +
    (prCount ? ` across ${prCount} PR(s)` : "") +
    ` over the last ${input.sinceDays} days and is proposing the corresponding memory updates. ` +
    `See **Memory promotion details** below for evidence and reasoning per candidate.`;

  const why =
    `Repeated review comments often encode implicit conventions that future agents and contributors should already know. ` +
    `This PR promotes ${count} such pattern(s) into durable repository memory so the same review feedback doesn't have to be re-issued PR after PR.`;

  const changeLines = input.candidates.map(
    (c) => `- \`${c.targetFile}\` — ${c.summary} (${c.id}, confidence ${c.confidence})`,
  );
  if (input.digestPath) {
    changeLines.push(`- \`${input.digestPath}\` — full scan digest (included for traceability)`);
  }
  const changes = changeLines.join("\n");

  const testing =
    `- Each draft was generated by LLM and requires human review before merge — read the appended content in each affected file.\n` +
    `- Compare against the reasoning and evidence in **Memory promotion details** below.` +
    (input.digestPath ? `\n- For the full picture (including skipped / \`needs_human_decision\` candidates), see \`${input.digestPath}\`.` : "");

  return { description, why, changes, testing };
}

export type SingleBodyInput = {
  candidate: PromotionCandidate & { targetFile: string };
  date: Date;
  prefilledHeader?: string;
};

export function buildSinglePrBody(input: SingleBodyInput): string {
  const isoDate = input.date.toISOString().split("T")[0];
  const sections: string[] = [];

  if (input.prefilledHeader && input.prefilledHeader.trim().length > 0) {
    sections.push(input.prefilledHeader.trimEnd());
  } else {
    const buckets = buildSingleBuckets(input);
    sections.push("## Summary", buckets.description);
    sections.push("## Why", buckets.why);
    sections.push("## Changes", buckets.changes);
    sections.push("## Testing", buckets.testing);
  }

  sections.push("## Memory promotion details");
  sections.push(`Generated by \`promote-cli\` v${VERSION} from scan run on ${isoDate}.`);
  sections.push(renderCandidateBlock(input.candidate, 1));
  sections.push("### Safety");
  sections.push(`- This PR was generated. The draft requires human review before merge.`);

  return sections.join("\n\n") + "\n";
}

function buildSingleBuckets(input: SingleBodyInput): Record<"description" | "why" | "changes" | "testing", string> {
  const c = input.candidate;
  const description =
    `Promote a repeated AI review pattern into \`${c.targetFile}\`: ${c.summary}. ` +
    `See **Memory promotion details** below for evidence.`;
  const why = c.reasoning;
  const changes = `- \`${c.targetFile}\` — ${c.summary} (${c.id}, confidence ${c.confidence})`;
  const testing =
    `- This draft was generated by LLM and requires human review before merge.\n` +
    `- Read the appended content in \`${c.targetFile}\` and compare with the reasoning in **Memory promotion details**.`;
  return { description, why, changes, testing };
}

function renderCandidateBlock(c: PromotionCandidate & { targetFile: string }, index: number): string {
  const header = `#### ${index}. ${c.summary}  *(target: ${c.target}, confidence: ${c.confidence})*`;
  const lines: string[] = [header];
  lines.push(`- File: \`${c.targetFile}\``);

  const evidence = (c.occurrences ?? []).slice(0, 5);
  if (evidence.length > 0) {
    const items = evidence.map((o) => {
      const path = o.path ? ` \`${o.path}\`` : "";
      return `[#${o.prNumber}](${o.url})${path}`;
    });
    const more = (c.occurrences?.length ?? 0) > 5 ? `, …and ${(c.occurrences?.length ?? 0) - 5} more` : "";
    lines.push(`- Evidence: ${items.join(", ")}${more}`);
  }

  if (c.reasoning) {
    lines.push(`- Reasoning: ${c.reasoning}`);
  }

  if (c.alternatives && c.alternatives.length > 0) {
    const alts = c.alternatives.map((a) => `${a.target}: ${a.reason}`).join("; ");
    lines.push(`- Alternatives considered: ${alts}`);
  }

  if (c.humanSignal) {
    const hs = c.humanSignal;
    const bits = [
      hs.agreementCount ? `${hs.agreementCount} agreed` : null,
      hs.rejectionCount ? `${hs.rejectionCount} dismissed` : null,
      hs.plusOneCount ? `👍 ${hs.plusOneCount}` : null,
      hs.minusOneCount ? `👎 ${hs.minusOneCount}` : null,
    ].filter(Boolean);
    if (bits.length > 0) {
      lines.push(`- Human signal: ${bits.join(" · ")}`);
    }
  }

  return lines.join("\n");
}

export function buildBundledPrTitle(date: Date, count: number): string {
  const isoDate = date.toISOString().split("T")[0];
  return `promote: ${count} memory update${count === 1 ? "" : "s"} from ${isoDate} scan`;
}

export function buildSinglePrTitle(candidate: { summary: string }): string {
  const trimmed = candidate.summary.length > 60 ? candidate.summary.slice(0, 57) + "..." : candidate.summary;
  return `promote: ${trimmed}`;
}
